simple_ingredients_page
yycorcino/meal-planner-app pull request #28
Opened 2024-11-01 20:02 UTC by jaredkeeler2

I want to update my simple_ingredients_page with the recent simple_lists_page code

2024-11-04 18:12 UTC, yycorcino requested changes
You will be needing to address the comments.

For some reason, on my end I'm having database related issues that I'm seeing for the first time:

```
Warning: Encountered two children with the same key, `.$Chicken Pesto Wraps`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

2024-11-04 18:12 UTC, yycorcino commented on package.json
> +    "expo-asset": "~10.0.10"
Add a comma at the end.

2024-11-04 18:12 UTC, yycorcino commented on app/(tabs)/lists.tsx
> +import DateTimePicker from "@react-native-community/datetimepicker";
Commenting this out fixes 1 of the errors to make app load.

2024-11-05 01:37 UTC, edgyasiankid commented
npm install
npm install react-native
npm install react-native-elements
npm install @react-native-community/datetimepicker
 prior to running program

2024-11-05 01:52 UTC, yycorcino approved these changes
Looks good!! With `package.json` updated and works go ahead and merge.

2024-11-05 03:49 UTC, merged